### ISSUE TITLE
Default theme cannot be restored

### ISSUE THREAD

**Issue by gortazar** [ujhelyiz/Presentation-Theme#3]
Hi,

I use Eclipse in my presentations too. I've been giving a try to your plugin and looks great. However, I have been unable to de-activate your theme: I select again Default theme in the Eclipse preferences, but it has no effect until I restart Eclipse.

Regards,
Patxi.

**Comment by ujhelyiz** [comment]
Thanks for the report, but I sadly could not reproduce it. I selected the theme, pressed apply, then reselected the default theme, and pressed apply, and the theme was restored.

Can you give me some more details (e.g. operating system, eclipse version, etc.) - without reproducing I won't be able to help.

Zoltán

**Comment by gortazar** [comment]
Zoltán,

I've tried again, and now everything works ok. Maybe it was a problem with my laptop because I suspended it and the problem appeared when I restored my session and tried to go back to default mode. I'm using Ubuntu, and Eclipse 3.6. 

Thanks for you quick response,
Patxi.

**Comment by ujhelyiz** [comment]
I'm glad it worked out well,
Zoltán
