### ISSUE TITLE
Documentation: How to install?

### ISSUE THREAD

**Issue by holyjak** [ujhelyiz/Presentation-Theme#4]
This looks very interesting, but which versions of Eclipse does it support and how do I add the theme to my Eclipse? Could you add this information to the README? Thanks a lot!

Best regards, Jakub Holy, Norway

**Comment by ujhelyiz** [comment]
Thank you for pointing out the issue. I updated the readme to point to the announcement blog post, and added our update site url as well.

**Comment by holyjak** [comment]
Great, thank you!
